protected/models/User.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

/**
 * This is the model class for table "user".
 *
 * The followings are the available columns in table 'user':
 * @property string $user_id
 * @property string $user_login
 * @property string $user_password
 * @property string $user_first_name
 * @property string $user_last_name
 * @property string $user_email_address
 * @property string $user_security_question_1
 * @property string $user_security_question_2
 * @property string $user_security_question_3
 * @property string $user_security_answer_1
 * @property string $user_security_answer_2
 * @property string $user_security_answer_3
 * @property string $user_status
 */
class User extends OADataSource
{

	// Class Constants
	// For DB enums
	const statusENABLED = 'enabled';
	const statusDISABLED = 'disabled';

	// For input validation
	public $user_password_confirm;
	public $user_password_current;

	/**
	 * Returns the static model of the specified AR class.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('user_id, user_login, user_password, user_email_address', 'required'),
			array('user_id', 'length', 'max'=>36),
			array('user_login, user_first_name, user_last_name', 'length', 'max'=>50),
			array('user_email_address, user_security_question_1, user_security_question_2, user_security_question_3, user_security_answer_1, user_security_answer_2, user_security_answer_3', 'length', 'max'=>255),
			array('user_status', 'length', 'max'=>9),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('user_id, user_login, user_password, user_first_name, user_last_name, user_email_address, user_security_question_1, user_security_question_2, user_security_question_3, user_security_answer_1, user_security_answer_2, user_security_answer_3, user_status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'roles' => array(
					self::MANY_MANY,
					'Role',
					'user_role(user_role_user_id,user_role_role_id)'
				),
			'user_api' => array(
					self::HAS_MANY,
					'UserApi',
					'user_api_user_id'
				),
			'user_history' => array(
					self::HAS_MANY,
					'UserHistory',
					'user_history_user_id'
				),
			'originators' => array(
					self::HAS_MANY,
					'Originator',
					'originator_user_id'
				),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'user_id' => 'User',
			'user_login' => 'Login',
			'user_password' => 'Password',
			'user_first_name' => 'First Name',
			'user_last_name' => 'Last Name',
			'user_email_address' => 'Email',
			'user_security_question_1' => 'Security Question 1',
			'user_security_question_2' => 'Security Question 2',
			'user_security_question_3' => 'Security Question 3',
			'user_security_answer_1' => 'Security Answer 1',
			'user_security_answer_2' => 'Security Answer 2',
			'user_security_answer_3' => 'Security Answer 3',
			'user_status' => 'Status',
		);
	}


	public function behaviors(){
		return array(
			'CEncryptionBehavior' => array(
				'class' => 'application.behaviors.CEncryptionBehavior',
				'attributeList' => array (
					'user_security_question_1'	=> 'crypt',
					'user_security_question_2'	=> 'crypt',
					'user_security_question_3'	=> 'crypt',
					'user_security_answer_1'	=> 'crypt',
					'user_security_answer_2'	=> 'crypt',
					'user_security_answer_3'	=> 'crypt',
				),
			),
			'CPasswordBehavior' => array(
				'class' => 'application.behaviors.CPasswordBehavior',
				'passwordAttribute' => 'user_password',
				'confirmAttribute' => 'user_password_confirm',
				'currentAttribute' => 'user_password_current',
			),
			'CUuidKeyBehavior' => array(
				'class' => 'application.behaviors.CUuidKeyBehavior',
				'attributeList' => array (
					'user_id',
				),
			),
			'CActiveLogBehavior' => array(
				'class' => 'application.behaviors.CActiveLogBehavior',
				'attributeList' => array (
					'user_id',
					'user_login',
					'user_first_name',
					'user_last_name',
					'user_email_address',
					'user_status',
				),
			),
		);
	}


	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('user_id',$this->user_id,true);

		$criteria->compare('user_login',$this->user_login,true);

		$criteria->compare('user_password',$this->user_password,true);

		$criteria->compare('user_first_name',$this->user_first_name,true);

		$criteria->compare('user_last_name',$this->user_last_name,true);

		$criteria->compare('user_email_address',$this->user_email_address,true);

		$criteria->compare('user_security_question_1',$this->user_security_question_1,true);

		$criteria->compare('user_security_question_2',$this->user_security_question_2,true);

		$criteria->compare('user_security_question_3',$this->user_security_question_3,true);

		$criteria->compare('user_security_answer_1',$this->user_security_answer_1,true);

		$criteria->compare('user_security_answer_2',$this->user_security_answer_2,true);

		$criteria->compare('user_security_answer_3',$this->user_security_answer_3,true);

		$criteria->compare('user_status',$this->user_status,true);

		$dataProvider = new CActiveDataProvider('User', array(
			'criteria'=>$criteria,
		));

		$dataProvider->sort->defaultOrder='user_login ASC';

		return $dataProvider;
	}

	public function validatePassword( $password )
	{
		$securityManager = Yii::app()->securityManager;
		if ( $this->user_password_current == sha1( $password ) )
		{
			return true;
		}
		if ( $this->user_password_current == hash_hmac( $securityManager->hashAlgorithm, $password, $securityManager->getValidationKey() ) )
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	public function isDisabled()
	{
		if ( $this->user_status == self::statusDISABLED )
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	public function hasRole( $roleName )
	{
		$role = Role::model()->findByName( $roleName );
		if ( $role && $role->isAssignedToUser( $this->user_id ) )
		{
			return true;
		}
	}

	public function grantRole( $roleName )
	{
		if ( ! $this->user_id || $this->hasRole( $roleName ) )
		{
			return;
		}

		if ( ! $role = Role::model()->findByName( $roleName ) )
		{
			throw new Exception( 'The role "' . $roleName . '" does not exist.' );
		}

		$userRole = UserRole::model();
		$userRole->user_role_user_id = $this->user_id;
		$userRole->user_role_role_id = $role->role_id;
		if ( ! $userRole->save() )
		{
			throw new Exception( 'Unable to save user role "' . $roleName . '" for user id ' . $this->user_id );
		}
	}

	public function revokeRole( $roleName )
	{
		if ( ! $this->user_id || $this->hasRole( $roleName ) )
		{
			return;
		}

		if ( ! $role = Role::model()->findByName( $roleName ) )
		{
			throw new Exception( 'The role "' . $roleName . '" does not exist.' );
		}

		$criteria = new CDbCriteria();	
		$criteria->addCondition( 'user_role_user_id = :user_id' );
		$criteria->addCondition( 'user_role_role_id = :role_id' );
		$criteria->params = array( ':user_id' => $this->user_id, ':role_id' => $role->role_id );		
		if ( $userRole = UserRole::model()->find( $criteria ) )
		{
			if ( ! $userRole->delete() )
			{
				throw new Exception( 'Unable to revoke role "' . $roleName . '" from user ' . $this->user_id );
			}
		}
		// Else, silently continue, as the role is no longer there
	}

	public function getUrl()
	{
		return Yii::app()->createUrl( 'user/view', array( 'id' => $this->getPrimaryKey() ) );
	}

	public function getOriginatorOptions()
	{
		$options = array();
		foreach ( $this->originators as $originator )
		{
			$options[ $originator->originator_id ] = $originator->originator_name;
		}
		return $options;
	}

	public function hasIatRole()
	{
		foreach ( $this->roles as $role )
		{
			if ( $role->role_iat_enabled )
			{
				return true;
			}
		}

		return false;
	}

	public function displayName()
	{
		return $this->user_first_name . ' ' . $this->user_last_name;
	}

	public function addRoleJoin( CDbCriteria $criteria )
	{
		$criteria->join .= ' INNER JOIN user_role ON ( user_role_user_id = :user_role_user_id AND user_role_role_id = role_id ) ';
		$criteria->params[ ':user_role_user_id' ] = $this->user_id;
	}

	public function addOriginatorJoin( CDbCriteria $criteria )
	{
		$criteria->join .= ' INNER JOIN originator ON ( originator_user_id = :originator_user_id ) ';
		$criteria->params[ ':originator_user_id' ] = $this->user_id;
	}

	public static function addUserJoin( CDbCriteria $criteria )
	{
		// Do nothing at this level...
	}

	public function isAuthorized( $object )
	{

		// Admin role always is authorized
		if ( $this->hasRole( 'administrator' ) )
		{
			return true;
		}

protected/controllers/UserController.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

class UserController extends OAController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('changePassword','update'),
				'users'=>array('@'),
			),
			array('allow', 
				'actions'=>array('index','view','create','update','search','delete','lookup'),
				'users'=>array('@'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$this->render('view',array(
			'model'=>$this->loadModel(),
		));
	}

	public function changePassword()
	{
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if ( $model->validate() )
			{
				$model->hashPassword();
				if($model->save())
					$this->redirect(array('view','id'=>$model->user_id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();

		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->user_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		//$criteria = array( 'order' => 'user_login ASC' );
		$dataProvider=new CActiveDataProvider( 'User', array(
				/*
				'pagination'=>array(
					'pageSize' => 10,
				),*/
				/* 'criteria' => $criteria, */
			));
		$dataProvider->sort->defaultOrder='user_login ASC';
		if ( Yii::app()->request->getParam( 'ajax' ) )
		{
			$this->showOAListView( $dataProvider );
			Yii::app()->end();
		}
		else
		{
			$this->render('index',array(
				'dataProvider'=>$dataProvider,
			));
		}
	}

	/**
	 * Manages all models.
	 */
	public function actionSearch()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		if ( Yii::app()->request->getParam( 'ajax' ) )
		{
			$this->showOAListView( $model->search() );
			Yii::app()->end();
		}
		else
		{
			$this->render('search',array(
				'model'=>$model,
			));
		}
	}

	public function actionLookup()
	{

		$term = Yii::app()->request->getParam( 'term' );

		if ( strlen( $term ) < 3 )
		{
			echo json_encode( array() );
			Yii::app()->end();
		}

		$sql = 'SELECT user_id, user_login FROM user WHERE user_login LIKE :user_login';
		$command = Yii::app()->db->createCommand( $sql );
		$command->bindValue( ':user_login', '%' . $term . '%', PDO::PARAM_STR );
		echo json_encode( $command->queryAll() );
		Yii::app()->end();
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		// Check for authorization to access the model
		if ( ! Yii::app()->user->model()->isAuthorized( $this->_model ) )
		{
			throw new CHttpException( 404, 'The requested page does not exist.' );
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

?>
<div class="form">

<?php $form=$this->beginWidget('OAActiveForm', array(
	'id'=>'user-form',
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'user_login'); ?>
		<?php echo $form->textField($model,'user_login',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'user_login'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'user_password'); ?>
		<?php echo $form->passwordField($model,'user_password',array('size'=>32,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'user_password'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'user_password_confirm'); ?>
		<?php echo $form->passwordField($model,'user_password_confirm',array('size'=>32,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'user_password_confirm'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'user_first_name'); ?>
		<?php echo $form->textField($model,'user_first_name',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'user_first_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'user_last_name'); ?>
		<?php echo $form->textField($model,'user_last_name',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'user_last_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'user_email_address'); ?>
		<?php echo $form->textField($model,'user_email_address',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'user_email_address'); ?>
	</div>
<? if ( ! $create ) : ?>

<div data-role="collapsible-set" data-theme="c" data-content-theme="a">
	<div data-role="collapsible">
		<h3><?php echo $model->getAttributeLabel('user_security_question_1'); ?></h3>
		<div class="row">
			<?php echo $form->labelEx($model,'user_security_question_1', array('label'=>'Question')); ?>
			<?php echo $form->textField($model,'user_security_question_1',array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'user_security_question_1'); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx($model,'user_security_answer_1', array('label'=>'Answer')); ?>
			<?php echo $form->textField($model,'user_security_answer_1',array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'user_security_answer_1'); ?>
		</div>
	</div>
	<div data-role="collapsible">
		<h3><?php echo $model->getAttributeLabel('user_security_question_2'); ?></h3>
		<div class="row">
			<?php echo $form->labelEx($model,'user_security_question_2', array('label'=>'Question')); ?>
			<?php echo $form->textField($model,'user_security_question_2',array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'user_security_question_2'); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx($model,'user_security_answer_2', array('label'=>'Answer')); ?>
			<?php echo $form->textField($model,'user_security_answer_2',array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'user_security_answer_2'); ?>
		</div>
	</div>
	<div data-role="collapsible">
		<h3><?php echo $model->getAttributeLabel('user_security_question_3'); ?></h3>
		<div class="row">
			<?php echo $form->labelEx($model,'user_security_question_3', array('label'=>'Question')); ?>
			<?php echo $form->textField($model,'user_security_question_3',array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'user_security_question_3'); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx($model,'user_security_answer_3', array('label'=>'Answer')); ?>
			<?php echo $form->textField($model,'user_security_answer_3',array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'user_security_answer_3'); ?>
		</div>
	</div>
</div>
<? endif; ?>

	<div class="row">
		<?php echo $form->labelEx($model,'user_status'); ?>
		<?php echo $form->listBox($model,'user_status',array('enabled'=>'enabled','suspended'=>'suspended'),
				array( /*'data-theme'=>'d',*/ 'data-icon'=>'gear', 'data-inline'=>'true', 'data-native-menu'=>'false' )
			 ); ?>
		<?php echo $form->error($model,'user_status'); ?>
	</div>

	<div class="row buttons">
		<div class="ui-grid-a">
			<div class="ui-block-a"><?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array( 'data-theme'=>'b') ); ?></div>
			<div class="ui-block-b"><?php echo CHtml::link('Cancel', Yii::app()->createUrl( 'user/view', array( 'id'=>$model->user_id ) ), array('data-role'=>'button', 'data-rel'=>'back')); ?></div>
		</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/user/_search.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

?>
<div class="wide form">

<?php $form=$this->beginWidget('OAActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'user_login'); ?>
		<?php echo $form->textField($model,'user_login',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_first_name'); ?>
		<?php echo $form->textField($model,'user_first_name',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_last_name'); ?>
		<?php echo $form->textField($model,'user_last_name',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_email_address'); ?>
		<?php echo $form->textField($model,'user_email_address',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_status'); ?>
		<?php echo $form->textField($model,'user_status',array('size'=>9,'maxlength'=>9)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search', array('data-inline'=>'true','data-theme'=>'b')); ?>
		<?php echo CHtml::resetButton('Clear', array('data-inline'=>'true') ); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_summarySubPanel.php
<ul data-role="listview" data-inset="true" data-theme="a" data-split-icon="gear" data-split-theme="a">
	<li data-role="list-divider">User</li>
	<li data-split-icon="gear" data-split-theme="a">
		<a href="<?php echo $this->createUrl( 'user/view', array( 'id' => $model->user_id ) ); ?>">
		<img src="/images/icons/large/user.png" />
		<h3><?= $model->user_login; ?></h3>
		<p><?= $model->displayName(); ?><?= $model->user_status == 'suspended' ? '(Suspended)' : ''; ?></p>
		<p><?= $model->user_email_address; ?></p></a>
		</a><a data-rel="dialog" href="<?php echo $this->createUrl( 'user/update', array( 'id' => $model->user_id ) ); ?>">Edit User</a>
	</li>
	<li class="list-footer-control" data-theme="a" data-icon="arrow-r">
		<a data-role="simpledialog-link" href="#">
			<h4>Security Questions</h4>
		</a>
		<div class="simpledialog-content">
			<ul class="small-thumb" data-role="listview" data-inset="false" data-theme="a">
				<li data-role="list-divider"><?= $model->user_login; ?></li>
				<li data-role="list-divider" data-theme="b">Question 1</li>
				<li><img src="/images/icons/question.png" /><?= $model->user_security_question_1; ?></li>
				<li><img src="/images/icons/answer.png" /><?= $model->user_security_answer_1; ?></li>
				<li data-role="list-divider" data-theme="b">Question 2</li>
				<li><img src="/images/icons/question.png" /><?= $model->user_security_question_2; ?></li>
				<li><img src="/images/icons/answer.png" /><?= $model->user_security_answer_2; ?></li>
				<li data-role="list-divider" data-theme="b">Question 3</li>
				<li><img src="/images/icons/question.png" /><?= $model->user_security_question_3; ?></li>
				<li><img src="/images/icons/answer.png" /><?= $model->user_security_answer_3; ?></li>
			</ul>
		</div>
	</li>
</ul>

protected/views/user/_view.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/
  if ( ! $this->currentPagerDivider  )
  {
	$this->prevPagerDivider = '';
  }
  else
  {
  	$this->prevPagerDivider = $this->currentPagerDivider;
  }
  $this->currentPagerDivider = substr( $data->user_login, 0, 1 );
  if ( Yii::app()->request->getParam('currentPagerDivider') != $this->currentPagerDivider && $this->currentPagerDivider != $this->prevPagerDivider ) :
?>
<?php if ( ! Yii::app()->request->getParam('User_sort') ): ?><li data-role="list-divider"><?= strtoupper( $this->currentPagerDivider ); ?></li><?php endif; ?>
<?php endif; ?>
<li>
	<a href="<?php echo $this->createUrl( 'user/view', array( 'id' => $data->user_id ) ); ?>">
	<img src="/images/icons/large/user.png" />
	<h3><?php echo $data->user_login; ?></h3>
	<p><strong><?php echo implode( ', ', array( CHtml::encode($data->user_last_name), CHtml::encode($data->user_first_name) ) ); ?></strong></p>
	<p><?php echo CHtml::encode($data->user_email_address); ?></p>
	<span class="ui-li-count"><?php echo CHtml::encode($data->user_status); ?></span>
	</a><a data-rel="dialog" href="<?php echo $this->createUrl( 'user/update', array( 'id' => $data->user_id ) ); ?>">Edit User</a>
</li>

protected/views/user/create.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

$this->stockMenus( array( 'list', 'search' ) );

?>

<h1>Create User</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'create'=>true)); ?>

protected/views/user/list.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

?>
<ul data-role="listview" data-inset="true" data-split-icon="gear" data-split-theme="a" data-count-theme="a" class="user-items">
<?php if ( count( $items ) > 0 ): ?>
	<li data-role="list-divider"><?= ( count( $items ) == 1 ) ? 'User' : 'Users'; ?></li>
<?php endif; ?>
<?php foreach ( $items as $item ): ?>
	<li>
		<a href="<?php echo $this->createUrl( 'user/view', array( 'id' => $item->user_id ) ); ?>">
		<img src="/images/icons/large/user.png" />
		<h3><?= $item->user_login; ?></h3>
		<p><?= $item->displayName(); ?></p>
		</a><a data-rel="dialog" href="<?php echo $this->createUrl( 'user/update', array( 'id' => $item->user_id ) ); ?>">Edit User</a>
	</li>
<?php endforeach; ?>
</ul>