protected/models/Role.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

/**
 * This is the model class for table "role".
 *
 * The followings are the available columns in table 'role':
 * @property string $role_id
 * @property string $role_name
 * @property string $role_description
 * @property integer $role_max_originator
 * @property integer $role_max_odfi
 * @property integer $role_max_daily_xfers
 * @property integer $role_max_daily_files
 * @property integer $role_max_daily_batches
 * @property integer $role_iat_enabled
 */
class Role extends OADataSource
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Role the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'role';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('role_id, role_name', 'required'),
			array('role_max_originator, role_max_odfi, role_max_daily_xfers, role_max_daily_files, role_max_daily_batches, role_iat_enabled', 'numerical', 'integerOnly'=>true, 'min'=>-1, 'max'=>1000 ),
			array('role_id', 'length', 'max'=>36),
			array('role_name', 'length', 'max'=>16),
			array('role_description', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('role_id, role_name, role_description, role_max_originator, role_max_odfi, role_max_daily_xfers, role_max_daily_files, role_max_daily_batches, role_iat_enabled', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'users' => array(
					self::MANY_MANY,
					'User',
					'user_role(user_role_role_id,user_role_user_id)'
				),
		);
	}

	public function behaviors(){
		return array(
			'CUuidKeyBehavior' => array(
				'class' => 'application.behaviors.CUuidKeyBehavior',
				'attributeList' => array (
					'role_id',
				),
			),
		);
	}


	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'role_id' => 'Role',
			'role_name' => 'Name',
			'role_description' => 'Description',
			'role_max_originator' => 'Max Originators',
			'role_max_odfi' => 'Max Odfi',
			'role_max_daily_xfers' => 'Max Daily Xfers',
			'role_max_daily_files' => 'Max Daily Files',
			'role_max_daily_batches' => 'Max Daily Batches',
			'role_iat_enabled' => 'International',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('role_id',$this->role_id,true);

		$criteria->compare('role_name',$this->role_name,true);

		$criteria->compare('role_description',$this->role_description,true);

		$criteria->compare('role_max_originator',$this->role_max_originator);

		$criteria->compare('role_max_odfi',$this->role_max_odfi);

		$criteria->compare('role_max_daily_xfers',$this->role_max_daily_xfers);

		$criteria->compare('role_max_daily_files',$this->role_max_daily_files);

		$criteria->compare('role_max_daily_batches',$this->role_max_daily_batches);

		$criteria->compare('role_iat_enabled',$this->role_iat_enabled);

		$dataProvider = new CActiveDataProvider('Role', array(
			'criteria'=>$criteria,
		));

		$dataProvider->sort->defaultOrder='role_name ASC';

		return $dataProvider;

	}

	/**
	 * Finds a role given its name
	 */
	static public function findByName( $roleName )
	{
		return self::model()->find( 'role_name=:role_name', array( ':role_name' => $roleName ) );
	}

	/**
	 * Checks to see if a user has this role assigned to them
	 * @return bool 
	 */
	public function isAssignedToUser( $userId )
	{
		if ( UserRole::model()->findByAttributes( 
				array( 
					'user_role_user_id' => $userId,
					'user_role_role_id' => $this->role_id
				)
			) )
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	public function displayIATEnabled()
	{
		if ( $this->role_iat_enabled )
		{
			return 'Yes';
		}
		else
		{
			return 'No';
		}
	}

}

protected/controllers/RoleController.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

class RoleController extends OAController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','search','delete'),
				'users'=>array('@'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$this->render('view',array(
			'model'=>$this->loadModel(),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Role;

		$this->performAjaxValidation($model);

		if(isset($_POST['Role']))
		{
			$model->attributes=$_POST['Role'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->role_id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();

		$this->performAjaxValidation($model);

		if(isset($_POST['Role']))
		{
			$model->attributes=$_POST['Role'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->role_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		//$criteria = array( 'order' => 'user_login ASC' );
		$dataProvider=new CActiveDataProvider( 'Role', array(
				/*
				'pagination'=>array(
					'pageSize' => 10,
				),*/
				/* 'criteria' => $criteria, */
			));
		$dataProvider->sort->defaultOrder='role_name ASC';
		if ( Yii::app()->request->getParam( 'ajax' ) )
		{
			$this->showOAListView( $dataProvider );
			Yii::app()->end();
		}
		else
		{
			$this->render('index',array(
				'dataProvider'=>$dataProvider,
			));
		}
	}


	/**
	 * Manages all models.
	 */
	public function actionSearch()
	{
		$model=new Role('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Role']))
			$model->attributes=$_GET['Role'];

		if ( Yii::app()->request->getParam( 'ajax' ) )
		{
			$this->showOAListView( $model->search() );
			Yii::app()->end();
		}
		else
		{
			$this->render('search',array(
				'model'=>$model,
			));
		}
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=Role::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='role-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/role/_form.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

?>
<div class="form">

<?php $form=$this->beginWidget('OAActiveForm', array(
	'id'=>'role-form',
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'role_name'); ?>
		<?php echo $form->textField($model,'role_name',array('size'=>16,'maxlength'=>16)); ?>
		<?php echo $form->error($model,'role_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'role_description'); ?>
		<?php echo $form->textArea($model,'role_description',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'role_description'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'role_max_originator'); ?>
		<?php echo $form->rangeField($model,'role_max_originator'); ?>
		<?php echo $form->error($model,'role_max_originator'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'role_max_odfi'); ?>
		<?php echo $form->rangeField($model,'role_max_odfi'); ?>
		<?php echo $form->error($model,'role_max_odfi'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'role_max_daily_xfers'); ?>
		<?php echo $form->rangeField($model,'role_max_daily_xfers'); ?>
		<?php echo $form->error($model,'role_max_daily_xfers'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'role_max_daily_files'); ?>
		<?php echo $form->rangeField($model,'role_max_daily_files'); ?>
		<?php echo $form->error($model,'role_max_daily_files'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'role_max_daily_batches'); ?>
		<?php echo $form->rangeField($model,'role_max_daily_batches'); ?>
		<?php echo $form->error($model,'role_max_daily_batches'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'role_iat_enabled'); ?>
		<?php echo $form->checkBox($model,'role_iat_enabled'); ?>
		<?php echo $form->error($model,'role_iat_enabled'); ?>
	</div>

	<div class="row buttons">
		<div class="ui-grid-a">
			<div class="ui-block-a"><?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('data-theme'=>'b') ); ?></div>
			<div class="ui-block-b"><?php echo CHtml::link('Cancel', Yii::app()->createUrl( 'role/view', array( 'id'=>$model->role_id ) ), array('data-role'=>'button', 'data-rel'=>'back')); ?></div>
		</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/role/_search.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

?>
<div class="wide form">

<?php $form=$this->beginWidget('OAActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'role_name'); ?>
		<?php echo $form->textField($model,'role_name',array('size'=>16,'maxlength'=>16)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'role_description'); ?>
		<?php echo $form->textArea($model,'role_description',array('rows'=>6, 'cols'=>50)); ?>
	</div>
<!--
	<div class="row">
		<?php echo $form->label($model,'role_max_originator'); ?>
		<?php echo $form->textField($model,'role_max_originator'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'role_max_odfi'); ?>
		<?php echo $form->textField($model,'role_max_odfi'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'role_max_daily_xfers'); ?>
		<?php echo $form->textField($model,'role_max_daily_xfers'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'role_max_daily_files'); ?>
		<?php echo $form->textField($model,'role_max_daily_files'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'role_max_daily_batches'); ?>
		<?php echo $form->textField($model,'role_max_daily_batches'); ?>
	</div>
-->
	<div class="row">
		<?php echo $form->label($model,'role_iat_enabled'); ?>
		<?php echo $form->checkBox($model,'role_iat_enabled'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search', array('data-inline'=>'true','data-theme'=>'b')); ?>
		<?php echo CHtml::resetButton('Clear', array('data-inline'=>'true') ); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/role/_summarySubPanel.php
<ul data-role="listview" data-inset="true" data-theme="a" data-split-icon="gear" data-split-theme="a">
	<li data-role="list-divider">Role</li>
	<li data-split-icon="gear" data-split-theme="a">
		<a href="<?php echo $this->createUrl( 'role/view', array( 'id' => $model->role_id ) ); ?>">
		<img src="/images/icons/large/role.png" />
		<h3><?= $model->role_name; ?></h3>
		<p><?= $model->role_description; ?></p>
		</a><a data-rel="dialog" href="<?php echo $this->createUrl( 'role/update', array( 'id' => $model->role_id ) ); ?>">Edit Role</a>
	</li>
	<li class="list-footer-control" data-theme="a" data-icon="arrow-r">
		<a data-role="simpledialog-link" href="#">
			<h4>View Details</h4>
		</a>
		<div class="simpledialog-content">
			<ul class="small-thumb" data-role="listview" data-inset="false" data-theme="a">
				<li data-role="list-divider"><?= $model->role_name; ?></li>
				<li><img src="/images/icons/originator.png" />Max Originators: <?= $model->role_max_originator; ?></li>
				<li><img src="/images/icons/bank.png" />Max ODFI Branches: <?= $model->role_max_odfi; ?></li>
				<li><img src="/images/icons/plugin.png" />Max Daily Transfers: <?= $model->role_max_daily_xfers; ?></li>
				<li><img src="/images/icons/achfile.png" />Max Daily Files: <?= $model->role_max_daily_files; ?></li>
				<li><img src="/images/icons/achbatch.png" />Max Daily Batches: <?= $model->role_max_daily_batches; ?></li>
				<li><img src="/images/icons/globe.png" />IAT Enabled: <?= $model->displayIATEnabled(); ?></li>
			</ul>
		</div>
	</li>
</ul>

protected/views/role/_view.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/
  if ( ! $this->currentPagerDivider  )
  {
	$this->prevPagerDivider = '';
  }
  else
  {
  	$this->prevPagerDivider = $this->currentPagerDivider;
  }
  $this->currentPagerDivider = substr( $data->role_name, 0, 1 );
  if ( Yii::app()->request->getParam('currentPagerDivider') != $this->currentPagerDivider && $this->currentPagerDivider != $this->prevPagerDivider ) :
?>
<?php if ( ! Yii::app()->request->getParam('Role_sort') ): ?><li data-role="list-divider"><?= strtoupper( $this->currentPagerDivider ); ?></li><?php endif; ?>
<?php endif; ?>
<li>
	<a href="<?php echo $this->createUrl( 'role/view', array( 'id' => $data->role_id ) ); ?>">
	<img src="/images/icons/large/role.png" />
	<h3><?php echo $data->role_name; ?></h3>
	<p><?php echo CHtml::encode($data->role_description); ?></p>
	<span class="ui-li-count"><?php echo ($data->role_iat_enabled) ? 'international' : 'domestic'; ?></span>
	</a><a data-rel="dialog" href="<?php echo $this->createUrl( 'role/update', array( 'id' => $data->role_id ) ); ?>">Edit Role</a>
</li>

protected/views/role/create.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

$this->breadcrumbs=array(
	'Roles'=>array('index'),
	'Create',
);

$this->stockMenus( array( 'list', 'search' ) );

?>

<h1>Create Role</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/role/index.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

$this->stockMenus( array( 'create', 'search' ) );

?>

<h1>Roles</h1>

<?php $this->showOAListView( $dataProvider, array( 'role_name', 'role_iat_enabled' ) ); ?>

protected/views/role/list.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

?>
<ul data-role="listview" data-inset="true" data-split-icon="gear" data-split-theme="a" data-count-theme="a" class="role-items">
<?php if ( count( $items ) > 0 ): ?>
	<li data-role="list-divider"><?= ( count( $items ) == 1 ) ? 'Role' : 'Roles'; ?></li>
<?php endif; ?>
<?php foreach ( $items as $item ): ?>
	<li>
		<a href="<?php echo $this->createUrl( 'role/view', array( 'id' => $item->role_id ) ); ?>">
		<img src="/images/icons/large/role.png" />
		<h3><?= $item->role_name; ?></h3>
		<p><?= $item->role_description; ?></p>
		</a>
	</li>
<?php endforeach; ?>
</ul>

protected/views/role/search.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

$this->breadcrumbs=array(
	'Roles'=>array('index'),
	'Manage',
);

$this->stockMenus( array( 'list','create' ) );

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('role-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Search Roles</h1>

<div data-role="collapsible" class="search-form">
	<h3>Search Options</h3>
<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->showOAListView( $model->search(), array( 'role_name', 'role_iat_enabled' ) ); ?>

protected/views/role/update.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

$this->breadcrumbs=array(
	'Roles'=>array('index'),
	$model->role_id=>array('view','id'=>$model->role_id),
	'Update',
);

$this->stockMenus( array( 'list','create','delete','view','search' ), $model->role_id );

?>

<h1>Update Role <?php echo $model->role_name; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/role/view.php
<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

$this->breadcrumbs=array(
	'Roles'=>array('index'),
	$model->role_id,
);

$this->stockMenus( array() );

$this->renderPartial( '_summarySubPanel', array( 'model'=>$model ) );
$this->renderPartial( '/user/list', array( 'items'=>$model->users, 'parent_id'=>$model->role_id ) );